# Generated by Django 5.2.8 on 2025-12-05 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_content_blogpage_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='cover_image',
        ),
    ]
